### ISSUE TITLE
[BUG] Safari: Double render

### ISSUE THREAD

**Issue by midzdotdev** [solidjs/solid-playground#150] opened 2023-08-06 09:45 UTC
In Safari on the first render, the playground seems to have the output rendered twice.

Below is an example screenshot for [this](https://playground.solidjs.com/anonymous/c672b993-b2b4-48f1-9ad5-080be2fa4830) playground, although it has happened consistently for the first render of any playground I've tried. Consequent renders behave as expected, without doubling of the content. This is using the `Client-side rendering` option for the `COMPILE MODE` setting.

<img width="1392" alt="image" src="https://github.com/solidjs/solid-playground/assets/14968094/2fd3520a-8065-4712-b98d-bb44ff36705f">

<details><summary>The code in the "Output" panel appears correct:</summary>

```tsx
import { template as _$template } from "solid-js/web";
import { insert as _$insert } from "solid-js/web";
import { createComponent as _$createComponent } from "solid-js/web";
import { For as _$For } from "solid-js/web";
const _tmpl$ = /*#__PURE__*/_$template(`<div><ul>`),
  _tmpl$2 = /*#__PURE__*/_$template(`<li><h1>`),
  _tmpl$3 = /*#__PURE__*/_$template(`<div>`);
import { render } from "solid-js/web";
import { children } from "solid-js";

// thinking of adding something like this to Solid's children helper
function toArray(v) {
  return Array.isArray(v) ? v : [v];
}
const Tab = props => props;
const Tabs = props => {
  const resolved = children(() => props.children);
  return (() => {
    const _el$ = _tmpl$(),
      _el$2 = _el$.firstChild;
    _$insert(_el$2, _$createComponent(_$For, {
      get each() {
        return toArray(resolved());
      },
      children: tab => (() => {
        const _el$3 = _tmpl$2(),
          _el$4 = _el$3.firstChild;
        _$insert(_el$4, () => tab.title);
        return _el$3;
      })()
    }));
    _$insert(_el$, _$createComponent(_$For, {
      get each() {
        return toArray(resolved());
      },
      children: tab => (() => {
        const _el$5 = _tmpl$3();
        _$insert(_el$5, () => tab.children);
        return _el$5;
      })()
    }), null);
    return _el$;
  })();
};
function App() {
  return _$createComponent(Tabs, {
    get children() {
      return [_$createComponent(Tab, {
        title: "Lemon",
        children: "Lemon is yellow"
      }), _$createComponent(Tab, {
        title: "Strawberry",
        children: "Strawberry is red"
      }), _$createComponent(Tab, {
        title: "Pear",
        children: "Pear is green"
      })];
    }
  });
}
render(() => _$createComponent(App, {}), document.getElementById("app"));
```

</details>

**Comment by modderme123** [comment] 2023-08-06 12:07
Hmm, I'm having trouble reproducing this on Safari locally, is it possible you have an extension that is causing strange behavior?

<img width="1766" alt="Screen Shot 2023-08-06 at 2 06 07 PM" src="https://github.com/solidjs/solid-playground/assets/14153763/04a2ec72-805f-44cb-a4dc-1e26162e981a">

**Comment by modderme123** [comment] 2023-11-08 18:54
Closing this because I can't reproduce

**Closed by modderme123** 2023-11-08 18:54 UTC
